//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Level
    {
        public int Inventory_ID { get; set; }
        public int InvLevel_Status_ID { get; set; }
        public string InvLevel_Description { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Inventory_Level_Status Inventory_Level_Status { get; set; }
    }
}
