//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Price
    {
        public int Price_ID { get; set; }
        public Nullable<int> Inventory_ID { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
