//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Inventory_Level = new HashSet<Inventory_Level>();
            this.Inventory_Price = new HashSet<Inventory_Price>();
            this.Order_Line = new HashSet<Order_Line>();
            this.Return_Sale = new HashSet<Return_Sale>();
            this.Sale_Line = new HashSet<Sale_Line>();
            this.Write_Off_Stock = new HashSet<Write_Off_Stock>();
            this.Write_Off_Line = new HashSet<Write_Off_Line>();
        }
    
        public int Inventory_ID { get; set; }
        public Nullable<int> InventoryType_ID { get; set; }
        public string Inventory_Name { get; set; }
        public string Inventory_Description { get; set; }
        public Nullable<int> Inventory_Quantity { get; set; }
        public Nullable<int> Minimum_Quantity { get; set; }
        public Nullable<int> StockTurn_ID { get; set; }
    
        public virtual Inventory_Type Inventory_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Level> Inventory_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Price> Inventory_Price { get; set; }
        public virtual Stock_Turns Stock_Turns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Line> Order_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Sale> Return_Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Line> Sale_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Write_Off_Stock> Write_Off_Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Write_Off_Line> Write_Off_Line { get; set; }
    }
}
