//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Line
    {
        public int ReturnSupp_Order_ID { get; set; }
        public int InvSuppOrder_ID { get; set; }
        public Nullable<int> Quanity { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
    
        public virtual Inventory_Supplier_Order Inventory_Supplier_Order { get; set; }
        public virtual Return_Supplier_Order Return_Supplier_Order { get; set; }
    }
}
