//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Sale_Line
    {
        public int Return_ID { get; set; }
        public int Sale_ID { get; set; }
        public Nullable<int> Return_Quantity { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public string Reason_For_Return { get; set; }
    
        public virtual Return_Sale Return_Sale { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
