//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TBMEntities : DbContext
    {
        public TBMEntities()
            : base("name=TBMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Book_Condition> Book_Condition { get; set; }
        public virtual DbSet<Book_Request> Book_Request { get; set; }
        public virtual DbSet<Book_Request_Line> Book_Request_Line { get; set; }
        public virtual DbSet<Book_Status> Book_Status { get; set; }
        public virtual DbSet<Book_Supplier> Book_Supplier { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Gender> Employee_Gender { get; set; }
        public virtual DbSet<Employee_Title> Employee_Title { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Inventory_Level> Inventory_Level { get; set; }
        public virtual DbSet<Inventory_Level_Status> Inventory_Level_Status { get; set; }
        public virtual DbSet<Inventory_Price> Inventory_Price { get; set; }
        public virtual DbSet<Inventory_Supplier> Inventory_Supplier { get; set; }
        public virtual DbSet<Inventory_Supplier_Order> Inventory_Supplier_Order { get; set; }
        public virtual DbSet<Inventory_Type> Inventory_Type { get; set; }
        public virtual DbSet<Order_Line> Order_Line { get; set; }
        public virtual DbSet<Order_Status> Order_Status { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Prospective_Book> Prospective_Book { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Purchase_Line> Purchase_Line { get; set; }
        public virtual DbSet<Received_Supplier_Order> Received_Supplier_Order { get; set; }
        public virtual DbSet<Return_Line> Return_Line { get; set; }
        public virtual DbSet<Return_Sale> Return_Sale { get; set; }
        public virtual DbSet<Return_Sale_Line> Return_Sale_Line { get; set; }
        public virtual DbSet<Return_Supplier_Order> Return_Supplier_Order { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Sale_Line> Sale_Line { get; set; }
        public virtual DbSet<Stock_Turns> Stock_Turns { get; set; }
        public virtual DbSet<TaxRate> TaxRates { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Write_Off_Line> Write_Off_Line { get; set; }
        public virtual DbSet<Write_Off_Stock> Write_Off_Stock { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
